# Generated by Django 3.1.1 on 2020-11-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
