# Generated by Django 3.1.1 on 2020-11-06 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfb_app', '0002_armys'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='army',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wfb_app.armys'),
        ),
    ]
