# Generated by Django 3.0.6 on 2020-11-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfb_app', '0003_units_army'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Hold the Ground'), (2, 'Breakthrough'), (3, 'Spoils of War'), (4, 'King of the Hill'), (5, 'Capture the Flag'), (6, 'Secure Target')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_armys', models.ManyToManyField(to='wfb_app.Armys')),
            ],
        ),
        migrations.CreateModel(
            name='GameResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_points', models.IntegerField()),
                ('objective', models.BooleanField(default=False)),
                ('game_rank', models.CharField(choices=[('master', 'Master'), ('local', 'Local'), ('home', 'Home')], max_length=16)),
                ('opponent', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('objective_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfb_app.Objectives')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfb_app.User')),
            ],
        ),
    ]
