# Generated by Django 3.1.3 on 2020-12-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfb_app', '0003_auto_20201204_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresults',
            name='objective_type',
            field=models.CharField(blank=True, choices=[(1, 'Hold the Ground'), (2, 'Breakthrough'), (3, 'Spoils of War'), (4, 'King of the Hill'), (5, 'Capture the Flag'), (6, 'Secure Target')], max_length=32),
        ),
    ]
