# Generated by Django 3.1.3 on 2020-12-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfb_app', '0004_auto_20201204_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresults',
            name='objective_type',
            field=models.CharField(choices=[(1, 'Hold the Ground'), (2, 'Breakthrough'), (3, 'Spoils of War'), (4, 'King of the Hill'), (5, 'Capture the Flag'), (6, 'Secure Target')], max_length=32, null=True),
        ),
    ]
